# ------------------
# theme settings
# ------------------
# theme: jekyll-theme-minimal
title: Emily Knight

# ------------------
# theme settings
# ------------------     
extra:
  social:
    - icon: fontawesome/solid/email
      link: mailto:emily.knight2@ucalgary.ca
      name: Email
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/emilyzknight/
      name: Linkedin

# ------------------
# navigation
# ------------------
nav:
  - Home: index.md
  - About Me:
    - CV: about-me/cv.md
    - Projects: about_me/projects.md
  - Intro to Circuits:
    - Overview: circuits/overview.md
    - Content: 
      - Overview: circuits/notes/overview.md
      - Introduction: circuits/notes/introduction.md
      - Systematic Circuit Analysis: circuits/notes/analysis.md
      - Operational Amplifiers: circuits/notes/op_amps.md
      - AC Circuits:
        - Overview: circuits/notes/ac_circuits.md
        - AC Power: circuits/notes/ac_power.md
      - DC Machines: circuits/notes/dc_machines.md
    - Question Types: circuits/question_types.md
  - Colorimetry:
    - Overview: colorimetry/overview.md